### ISSUE TITLE
Migrate repo to Camunda org

### ISSUE THREAD

**Issue by MaxTru** [camunda/zeebe-bpmn-moddle#34]
**What to do**
Migrate this repo to https://github.com/camunda

**Why to do it**
* We don't use camunda-cloud anymore (at least we should not). Camunda Cloud is now C8 and integral part of Camunda Platform.
* Also other core components (e.g., zeebe) now live in `camunda` org

**Comment by nikku** [comment]
@barmac Is this something you can also take on this week?

**Comment by nikku** [comment]
Transfered. If you could take on renamings (if needed)! :)

**Comment by nikku** [comment]
https://github.com/camunda/zeebe-bpmn-moddle/pull/35#pullrequestreview-1082266115 :+1: :smile:

**Comment by barmac** [comment]
@nikku I had to manually remove the label. Either it's a hiccup or we need to add it to wuffle. It seems I can't do that for camunda organization.

**Comment by nikku** [comment]
Needs to be manually added I believe. Done.
