### ISSUE TITLE
Add support for retry backoff

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe-bpmn-moddle#42]
Since [the BPMN API for retry backoff negotiated](https://github.com/camunda/zeebe/pull/11339#pullrequestreview-1241821331) we are ready to implement it in the Camunda Modeler, for example. Adding support for the retry backoff in this library would be the first step, I suppose.

P.S. I am ready to implement this issue, you can assign this to me :)

**Comment by nikku** [comment]
Closing this issue. Let's re-open it once we have clarity what the desired editor support looks like. Let's use https://github.com/camunda/camunda-modeler/issues/3419 to define that support.
