### ISSUE TITLE
Support `zeebe:versionTag`

### ISSUE THREAD

**Issue by wollefitz** [camunda/zeebe-bpmn-moddle#59]
__Is your feature request related to a problem? Please describe__

Support for the new `zeebe:versionTag` property to be implemented as part of https://github.com/camunda/product-hub/issues/435.

  ```xml
  <bpmn:process id="test-process" name="test process" isExecutable="true">
      <bpmn:extensionElements>
          <zeebe:versionTag value="v1.0.0" />
      </bpmn:extensionElements>
  </bpmn:process>
  ```

__Describe the solution you'd like__

* [ ] `zeebe:versionTag` is recognized by moddle

__Describe alternatives you've considered__

None.

----

Related to https://github.com/camunda/product-hub/issues/435
Related to https://github.com/camunda/web-modeler/issues/9581

**Comment by nikku** [comment]
@wollefitz Usually the team adds `ready` as part of our [regular inbox grooming](https://github.com/bpmn-io/internal-docs/blob/main/development/INBOX_GROOMING.md). What would be needed from your end is to establish context, only. As I understood this [would unblock some users right now](https://camunda.slack.com/archives/C032H77434N/p1719424819646829).

**Comment by wollefitz** [comment]
> As I understood this [would unblock some users right now](https://camunda.slack.com/archives/C032H77434N/p1719424819646829).

Correct, this would unblock us from delivering https://github.com/camunda/web-modeler/issues/9581 to users.

**Comment by wollefitz** [comment]
@philippfromme Do you already have a rough idea of when you expect this to be available? As mentioned above, this currently blocks us from proceeding with some of our epics planned for the next alpha release.

**Comment by philippfromme** [comment]
I will look into this tomorrow. Should be available this week.
